name: Image Optimisation

on:
  push:
    branches: [main]
    paths:
      - "images/**/*.jpg"
      - "images/**/*.jpeg"
      - "images/**/*.png"
      - "images/**/*.webp"
  workflow_dispatch:

jobs:
  optimise-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Calibre Image Actions
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: false
          jpegQuality: "80"
          jpegProgressive: true
          pngQuality: "80"
          webpQuality: "80"
          ignorePaths: "images/**/logo*,images/**/*no-background*"
